#Instructions on using pandas and what dependencies to install were generated by ChatGPT

import pandas as pd

myxls = pd.ExcelFile(r"C:\Users\berni\Documents\GitHub\DATA1002-Sports-Analysis\AusGov Sports Data\data\41770do002_201314.xls")

for sheet_name in myxls.sheet_names:
    df = pd.read_excel(myxls, sheet_name=sheet_name)
    df.to_csv(f"{sheet_name}.csv", index=False)
    print(f"Saved {sheet_name}.csv")